language: python
dist: trusty
addons: # get google-chrome-stable
    chrome: stable
install:
    - pip install Selenium

    
python:
  - "3.6.4"
script:
    - cd lib
    - sudo mv chromedriver /usr/local/bin/chromedriver
    - sudo chmod +x /usr/local/bin/chromedriver
    - whereis google-chrome-stable
    - whereis chromedriver
    - cd ../src
    - ./run_test_kibana.sh


